spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9094
    consumer:
      # latest, earliest
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: messagenoloss
    listener:
      ack-mode: manual
#      concurrency: 3
    producer:
      retries: 3  #  重试次数
      acks: all
      client-id: ${spring.application.name}
    admin:
      fail-fast: true

kafka:
  topics:
    - name: test-topic
      num-partitions: 3
      replication-factor: 1
    - name: test-topic-2
      num-partitions: 3
      replication-factor: 1